import { League_Spartan, Montserrat } from 'next/font/google'
import type { Metadata } from "next";
import "./globals.css";
import QueryProvider from '@/providers/QueryProvider';



const montserrat = Montserrat({
  subsets: ['latin'],
})

const leagueSpartan = League_Spartan({ 
  subsets: ["latin"],
  variable: "--font-spartan",    // Nombre de la variable para League Spartan
});

export const metadata: Metadata = {
  title: "Siae-NFC",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} ${leagueSpartan.variable}`} >
        <QueryProvider>
        {children}
        </QueryProvider>
      </body>
    </html>
  );
}
